name: Tests Automatisés (CI)

on:
  workflow_dispatch:
  push:
    branches: [ "main", "master" ]
    paths:
      - '**' 
  pull_request:
    branches: [ "main", "master" ]

jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Récupération du code
        uses: actions/checkout@v4

      - name: Installation Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Installation des dépendances Backend
        working-directory: ./backend
        - name: Installation des dépendances Backend
        working-directory: ./backend
        run: |
          python -m pip install --upgrade pip
          pip install fastapi uvicorn sqlmodel pytest httpx azure-storage-blob python-multipart python-dotenv psycopg2-binary pymssql

      - name: Lancement des Tests Backend
        working-directory: ./backend
        run: |
          pytest -v

  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Récupération du code
        uses: actions/checkout@v4

      - name: Installation Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Installation des dépendances Frontend
        working-directory: ./frontend
        run: npm ci

      - name: Lancement des Tests Frontend
        working-directory: ./frontend
        run: npm test
        env:
          CI: true