name: Tests Automatisés (CI)

# Déclenche les tests à chaque push sur la branche main ou lors d'une Pull Request
on:
  push:
    branches: [ "main", "master" ]
    paths:
      - 'cloud/**'
  pull_request:
    branches: [ "main", "master" ]

jobs:
  # TEST BACKEND
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Récupération du code
        uses: actions/checkout@v4

      - name: Installation Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Installation des dépendances Backend
        working-directory: ./cloud/backend
        run: |
          python -m pip install --upgrade pip
          # Installe les libs requises + celles de test
          pip install fastapi uvicorn sqlmodel pytest httpx azure-storage-blob python-multipart

      - name: Lancement des Tests Backend
        working-directory: ./cloud/backend
        run: |
          pytest -v

  # JOB 2 : TEST FRONTEND
  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Récupération du code
        uses: actions/checkout@v4

      - name: Installation Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Installation des dépendances Frontend
        working-directory: ./cloud/frontend
        run: npm ci

      - name: Lancement des Tests Frontend
        working-directory: ./cloud/frontend
        run: npm test
        env:
          CI: true